spring:
    liquibase:
        change-log: classpath:liquibase/changelog.yml
    profiles:
        active: @profileActive@
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
server:
    port: 80