spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/modsen
        username: postgres
        password: 172143
    hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
            auto: none